### ISSUE TITLE
SSHD

### ISSUE THREAD

**Issue by tomgreenhill** [Dees7/openstora#1]
Hey, I've just started poking around my newly (old) bought Stora and came across this. Do you happen to know where I can download the SSHD that is described [here](https://github.com/Dees7/openstora/blob/master/pages/Sshd_substitution.md) please?Thanks!

**Comment by Dees7** [comment]
Hello. 
Unfortunately I don't have. Try "hard way" or use keys.
Also you can try use ssh from [Openware ](http://ipkg.nslu2-linux.org/feeds/optware/cs08q1armel/cross/stable/openssh_5.9p1-1_arm.ipk)

**Comment by tomgreenhill** [comment]
Awesome thanks will give it a go!
